// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AuditConnection struct {
	Entries []*AuditEntry `json:"entries"`
	HasMore bool          `json:"hasMore"`
}

type AuditEntry struct {
	ID         string         `json:"id"`
	Action     string         `json:"action"`
	EntityType string         `json:"entityType"`
	EntityID   string         `json:"entityID"`
	Actor      *string        `json:"actor,omitempty"`
	Detail     map[string]any `json:"detail,omitempty"`
	CreatedAt  string         `json:"createdAt"`
}

type ContextResult struct {
	Node      *Node   `json:"node"`
	Neighbors []*Node `json:"neighbors"`
	Edges     []*Edge `json:"edges"`
}

type CreateEdgeInput struct {
	Source     string         `json:"source"`
	Target     string         `json:"target"`
	Relation   string         `json:"relation"`
	Properties map[string]any `json:"properties,omitempty"`
	Weight     *float64       `json:"weight,omitempty"`
}

type CreateNodeInput struct {
	ID         *string        `json:"id,omitempty"`
	Type       string         `json:"type"`
	Label      string         `json:"label"`
	Properties map[string]any `json:"properties,omitempty"`
}

type Edge struct {
	Source        string         `json:"source"`
	Target        string         `json:"target"`
	Relation      string         `json:"relation"`
	Properties    map[string]any `json:"properties,omitempty"`
	Weight        float64        `json:"weight"`
	AccessCount   int            `json:"accessCount"`
	SalienceScore float64        `json:"salienceScore"`
	UserBoosted   bool           `json:"userBoosted"`
	CreatedAt     string         `json:"createdAt"`
	UpdatedAt     string         `json:"updatedAt"`
	SourceNode    *Node          `json:"sourceNode,omitempty"`
	TargetNode    *Node          `json:"targetNode,omitempty"`
}

type EdgeConnection struct {
	Edges   []*Edge `json:"edges"`
	HasMore bool    `json:"hasMore"`
}

type Mutation struct {
}

type NeighborResult struct {
	Nodes []*Node `json:"nodes"`
	Edges []*Edge `json:"edges"`
}

type Node struct {
	ID            string         `json:"id"`
	Type          string         `json:"type"`
	Label         string         `json:"label"`
	Properties    map[string]any `json:"properties,omitempty"`
	AccessCount   int            `json:"accessCount"`
	SalienceScore float64        `json:"salienceScore"`
	UserBoosted   bool           `json:"userBoosted"`
	CreatedAt     string         `json:"createdAt"`
	UpdatedAt     string         `json:"updatedAt"`
	Edges         []*Edge        `json:"edges"`
	Neighbors     []*Node        `json:"neighbors"`
}

type NodeConnection struct {
	Nodes   []*Node `json:"nodes"`
	HasMore bool    `json:"hasMore"`
}

type Query struct {
}

type SearchResult struct {
	Node  *Node   `json:"node"`
	Score float64 `json:"score"`
}

type TraverseResult struct {
	Nodes []*Node `json:"nodes"`
	Edges []*Edge `json:"edges"`
}

type UpdateEdgeInput struct {
	Properties map[string]any `json:"properties,omitempty"`
	Weight     *float64       `json:"weight,omitempty"`
}

type UpdateNodeInput struct {
	Type       *string        `json:"type,omitempty"`
	Label      *string        `json:"label,omitempty"`
	Properties map[string]any `json:"properties,omitempty"`
}
