package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// SourceNode is the resolver for the sourceNode field.
func (r *edgeResolver) SourceNode(ctx context.Context, obj *Edge) (*Node, error) {
	tid, err := TenantIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	n, err := r.NodeSvc.GetNode(ctx, tid, obj.Source)
	if err != nil {
		return nil, err
	}
	return nodeToGQL(n), nil
}

// TargetNode is the resolver for the targetNode field.
func (r *edgeResolver) TargetNode(ctx context.Context, obj *Edge) (*Node, error) {
	tid, err := TenantIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	n, err := r.NodeSvc.GetNode(ctx, tid, obj.Target)
	if err != nil {
		return nil, err
	}
	return nodeToGQL(n), nil
}

// Edges is the resolver for the edges field.
func (r *nodeResolver) Edges(ctx context.Context, obj *Node, relation *string, limit *int) ([]*Edge, error) {
	tid, err := TenantIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	// Fetch edges where this node is the source.
	edges, _, err := r.EdgeSvc.ListEdges(ctx, tid, obj.ID, "", derefStr(relation), deref(limit, 50), 0)
	if err != nil {
		return nil, err
	}
	return edgesToGQL(edges), nil
}

// Neighbors is the resolver for the neighbors field.
func (r *nodeResolver) Neighbors(ctx context.Context, obj *Node, limit *int) ([]*Node, error) {
	tid, err := TenantIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.GraphSvc.Neighbors(ctx, tid, obj.ID, deref(limit, 50))
	if err != nil {
		return nil, err
	}
	return nodesToGQL(result.Nodes), nil
}

// Edge returns EdgeResolver implementation.
func (r *Resolver) Edge() EdgeResolver { return &edgeResolver{r} }

// Node returns NodeResolver implementation.
func (r *Resolver) Node() NodeResolver { return &nodeResolver{r} }

type edgeResolver struct{ *Resolver }
type nodeResolver struct{ *Resolver }
